### ISSUE TITLE
About ASCII

### ISSUE THREAD

**Issue by Sh1mar** [Kappamalone/Asciifier#1]
Hello this shimar, this may be annoying but just have a question why did you use a python dictionary when you could have used the ord() function to get the ASCII code and chr() function to get the ASCII characters, and I had a small doubt about is this program capable of taking images above the set height and width that you have given. Sorry I just had some doubts

**Comment by Kappamalone** [comment]
The reason behind not using the inbuilt functions is that I'm using the ascii luminance chart from here: https://youtu.be/DEqXNfs_HhY?t=45. Basically, brighter pixels need an ascii character that is visible, and darker characters need an ascii character that is less visible. As for the dimensions of the returned image, it's mostly handled by the PIL library, and to be honest I just fiddled around with numbers until I got the output I wanted.

**Comment by Sh1mar** [comment]
Got it thanks for  the information sorry I responded late
